"""Create dwh schema and tables

Revision ID: 012387aa578e
Revises: 
Create Date: 2026-05-14 22:05:47.211628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '012387aa578e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_artists',
    sa.Column('artist_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('spotify_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('genres', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('loaded_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('artist_id'),
    sa.UniqueConstraint('spotify_id'),
    schema='dwh'
    )
    op.create_table('dim_users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('spotify_id', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('product', sa.String(length=20), nullable=True),
    sa.Column('spotify_access_token', sa.Text(), nullable=True),
    sa.Column('spotify_refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('loaded_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('spotify_id'),
    schema='dwh'
    )
    op.create_table('etl_audit',
    sa.Column('audit_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('spotify_user_id', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('finished_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('users_new', sa.Integer(), nullable=True),
    sa.Column('artists_new', sa.Integer(), nullable=True),
    sa.Column('artists_skipped', sa.Integer(), nullable=True),
    sa.Column('tracks_new', sa.Integer(), nullable=True),
    sa.Column('tracks_skipped', sa.Integer(), nullable=True),
    sa.Column('history_new', sa.Integer(), nullable=True),
    sa.Column('history_skipped', sa.Integer(), nullable=True),
    sa.Column('cursor_after_ms', sa.BigInteger(), nullable=True),
    sa.Column('cursor_next_ms', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('audit_id'),
    schema='dwh'
    )
    op.create_table('pkce_sessions',
    sa.Column('state', sa.String(length=128), nullable=False),
    sa.Column('verifier', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('state'),
    schema='public'
    )
    op.create_table('dim_tracks',
    sa.Column('track_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('spotify_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('album_name', sa.String(length=255), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('explicit', sa.Boolean(), nullable=True),
    sa.Column('loaded_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['dwh.dim_artists.artist_id'], ),
    sa.PrimaryKeyConstraint('track_id'),
    sa.UniqueConstraint('spotify_id'),
    schema='dwh'
    )
    op.create_table('fact_listening_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('played_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('hour_of_day', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.String(length=10), nullable=True),
    sa.Column('context_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['dwh.dim_artists.artist_id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['dwh.dim_tracks.track_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['dwh.dim_users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'played_at', name='uq_user_played_at'),
    schema='dwh'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fact_listening_history', schema='dwh')
    op.drop_table('dim_tracks', schema='dwh')
    op.drop_table('pkce_sessions', schema='public')
    op.drop_table('etl_audit', schema='dwh')
    op.drop_table('dim_users', schema='dwh')
    op.drop_table('dim_artists', schema='dwh')
    # ### end Alembic commands ###
