"""create dwh tables

Revision ID: 24bc08b5aa2c
Revises: 
Create Date: 2026-05-10 17:53:42.604929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24bc08b5aa2c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS dwh")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_artists',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('spotify_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('genres', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('loaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('artist_id'),
    sa.UniqueConstraint('spotify_id'),
    schema='dwh'
    )
    op.create_index(op.f('ix_dwh_dim_artists_artist_id'), 'dim_artists', ['artist_id'], unique=False, schema='dwh')
    op.create_table('dim_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('spotify_id', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('product', sa.String(length=20), nullable=True),
    sa.Column('spotify_access_token', sa.Text(), nullable=True),
    sa.Column('spotify_refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('loaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('spotify_id'),
    schema='dwh'
    )
    op.create_index(op.f('ix_dwh_dim_users_user_id'), 'dim_users', ['user_id'], unique=False, schema='dwh')
    op.create_table('etl_audit',
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('spotify_user_id', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('users_new', sa.Integer(), nullable=True),
    sa.Column('artists_new', sa.Integer(), nullable=True),
    sa.Column('artists_skipped', sa.Integer(), nullable=True),
    sa.Column('tracks_new', sa.Integer(), nullable=True),
    sa.Column('tracks_skipped', sa.Integer(), nullable=True),
    sa.Column('history_new', sa.Integer(), nullable=True),
    sa.Column('history_skipped', sa.Integer(), nullable=True),
    sa.Column('cursor_after_ms', sa.BIGINT(), nullable=True),
    sa.Column('cursor_next_ms', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('audit_id'),
    schema='dwh'
    )
    op.create_index(op.f('ix_dwh_etl_audit_audit_id'), 'etl_audit', ['audit_id'], unique=False, schema='dwh')
    op.create_table('pkce_sessions',
    sa.Column('state', sa.String(length=128), nullable=False),
    sa.Column('verifier', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('state')
    )
    op.create_table('dim_tracks',
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('spotify_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('album_name', sa.String(length=255), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('explicit', sa.Boolean(), nullable=True),
    sa.Column('loaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['dwh.dim_artists.artist_id'], ),
    sa.PrimaryKeyConstraint('track_id'),
    sa.UniqueConstraint('spotify_id'),
    schema='dwh'
    )
    op.create_index(op.f('ix_dwh_dim_tracks_track_id'), 'dim_tracks', ['track_id'], unique=False, schema='dwh')
    op.create_table('fact_listening_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('played_at', sa.DateTime(), nullable=False),
    sa.Column('hour_of_day', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.String(length=10), nullable=True),
    sa.Column('context_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['dwh.dim_artists.artist_id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['dwh.dim_tracks.track_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['dwh.dim_users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dwh'
    )
    op.create_index(op.f('ix_dwh_fact_listening_history_id'), 'fact_listening_history', ['id'], unique=False, schema='dwh')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dwh_fact_listening_history_id'), table_name='fact_listening_history', schema='dwh')
    op.drop_table('fact_listening_history', schema='dwh')
    op.drop_index(op.f('ix_dwh_dim_tracks_track_id'), table_name='dim_tracks', schema='dwh')
    op.drop_table('dim_tracks', schema='dwh')
    op.drop_table('pkce_sessions')
    op.drop_index(op.f('ix_dwh_etl_audit_audit_id'), table_name='etl_audit', schema='dwh')
    op.drop_table('etl_audit', schema='dwh')
    op.drop_index(op.f('ix_dwh_dim_users_user_id'), table_name='dim_users', schema='dwh')
    op.drop_table('dim_users', schema='dwh')
    op.drop_index(op.f('ix_dwh_dim_artists_artist_id'), table_name='dim_artists', schema='dwh')
    op.drop_table('dim_artists', schema='dwh')
    # ### end Alembic commands ###
